In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
file=r'chipotle.tsv'

In [42]:
data=pd.read_csv(file, sep='\t')

In [43]:
data.head(2)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39

In [12]:
data.shape

(4622, 5)

In [13]:
data.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [14]:
data.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [16]:
data.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [24]:
def temp(val):
    val = str(val)
    x = ""
    for char in val:
        if char == '.':
            x = x+char
        elif char.isdigit():
            x = x+char
    if len(x)> 0:
        return x
    else:
        return np.nan

In [44]:
data['item_price'] = data['item_price'].apply(temp)

In [45]:
data.rename(columns = {'item_price':'item_price'},inplace = True)

In [39]:
data.head(2)

,order_id,quantity,item_name,choice_description,item_price in $
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39

In [46]:
data['item_price'] = data['item_price'].astype('float')

In [47]:
data.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [53]:
'''Task A: Identify the star product for the company?'''
data.groupby('item_name').agg({'quantity':'sum','item_price':'sum'}).sort_values(by = 'quantity', ascending = False)

                                       quantity  item_price
item_name
Chicken Bowl                                761     7342.73
Chicken Burrito                             591     5575.82
Chips and Guacamole                         506     2201.04
Steak Burrito                               386     3851.43
Canned Soft Drink                           351      438.75
Chips                                       230      494.34
Steak Bowl                                  221     2260.19
Bottled Water                               211      302.56
Chips and Fresh Tomato Salsa                130      361.36
Canned Soda                                 126      137.34
Chicken Salad Bowl                          123     1228.75
Chicken Soft Tacos                          120     1108.09
Side of Chips                               110      185.90
Veggie Burrito                               97      934.77
Barbacoa Burrito                             91      894.75
Veggie Bowl                                  87      867.99
Carnitas Bowl                                71      736.71
Barbacoa Bowl                                66      672.36
Carnitas Burrito                             60      597.83
Steak Soft Tacos                             56      536.05
6 Pack Soft Drink                            55      356.95
Chips and Tomatillo Red Chili Salsa          50      147.50
Chicken Crispy Tacos                         50      472.13
Chips and Tomatillo Green Chili Salsa        45      132.75
Carnitas Soft Tacos                          40      375.94
Steak Crispy Tacos                           36      357.34
Chips and Tomatillo-Green Chili Salsa        33       78.87
Steak Salad Bowl                             31      343.59
Nantucket Nectar                             29       98.31
Chips and Tomatillo-Red Chili Salsa          25       59.75
Barbacoa Soft Tacos                          25      250.46
Chips and Roasted Chili Corn Salsa           23       67.85
Izze                                         20       67.80
Veggie Salad Bowl                            18      182.50
Chips and Roasted Chili-Corn Salsa           18       43.02
Barbacoa Crispy Tacos                        12      120.21
Barbacoa Salad Bowl                          10      106.40
Chicken Salad                                 9       81.09
Carnitas Crispy Tacos                         8       77.96
Veggie Soft Tacos                             8       73.96
Burrito                                       6       44.40
Veggie Salad                                  6       50.94
Carnitas Salad Bowl                           6       66.34
Bowl                                          4       29.60
Steak Salad                                   4       35.66
Salad                                         2       14.80
Crispy Tacos                                  2       14.80
Chips and Mild Fresh Tomato Salsa             1        3.00
Carnitas Salad                                1        8.99
Veggie Crispy Tacos                           1        8.49

In [ ]:
# Chicken Bowl is the star Product. It is sold the most

In [15]:
data['choice_description'].nunique()

1043

In [55]:
'''Task B: What’s the most selling product and most expensive product?'''
data.groupby('item_name').agg({'quantity':'sum'}).sort_values(by = 'quantity', ascending = False)

                                       quantity
item_name
Chicken Bowl                                761
Chicken Burrito                             591
Chips and Guacamole                         506
Steak Burrito                               386
Canned Soft Drink                           351
Chips                                       230
Steak Bowl                                  221
Bottled Water                               211
Chips and Fresh Tomato Salsa                130
Canned Soda                                 126
Chicken Salad Bowl                          123
Chicken Soft Tacos                          120
Side of Chips                               110
Veggie Burrito                               97
Barbacoa Burrito                             91
Veggie Bowl                                  87
Carnitas Bowl                                71
Barbacoa Bowl                                66
Carnitas Burrito                             60
Steak Soft Tacos                             56
6 Pack Soft Drink                            55
Chips and Tomatillo Red Chili Salsa          50
Chicken Crispy Tacos                         50
Chips and Tomatillo Green Chili Salsa        45
Carnitas Soft Tacos                          40
Steak Crispy Tacos                           36
Chips and Tomatillo-Green Chili Salsa        33
Steak Salad Bowl                             31
Nantucket Nectar                             29
Chips and Tomatillo-Red Chili Salsa          25
Barbacoa Soft Tacos                          25
Chips and Roasted Chili Corn Salsa           23
Izze                                         20
Veggie Salad Bowl                            18
Chips and Roasted Chili-Corn Salsa           18
Barbacoa Crispy Tacos                        12
Barbacoa Salad Bowl                          10
Chicken Salad                                 9
Carnitas Crispy Tacos                         8
Veggie Soft Tacos                             8
Burrito                                       6
Veggie Salad                                  6
Carnitas Salad Bowl                           6
Bowl                                          4
Steak Salad                                   4
Salad                                         2
Crispy Tacos                                  2
Chips and Mild Fresh Tomato Salsa             1
Carnitas Salad                                1
Veggie Crispy Tacos                           1

In [57]:
data.groupby('item_name').agg({'item_price':'sum'}).sort_values(by = 'item_price', ascending = False)

                                       item_price
item_name
Chicken Bowl                              7342.73
Chicken Burrito                           5575.82
Steak Burrito                             3851.43
Steak Bowl                                2260.19
Chips and Guacamole                       2201.04
Chicken Salad Bowl                        1228.75
Chicken Soft Tacos                        1108.09
Veggie Burrito                             934.77
Barbacoa Burrito                           894.75
Veggie Bowl                                867.99
Carnitas Bowl                              736.71
Barbacoa Bowl                              672.36
Carnitas Burrito                           597.83
Steak Soft Tacos                           536.05
Chips                                      494.34
Chicken Crispy Tacos                       472.13
Canned Soft Drink                          438.75
Carnitas Soft Tacos                        375.94
Chips and Fresh Tomato Salsa               361.36
Steak Crispy Tacos                         357.34
6 Pack Soft Drink                          356.95
Steak Salad Bowl                           343.59
Bottled Water                              302.56
Barbacoa Soft Tacos                        250.46
Side of Chips                              185.90
Veggie Salad Bowl                          182.50
Chips and Tomatillo Red Chili Salsa        147.50
Canned Soda                                137.34
Chips and Tomatillo Green Chili Salsa      132.75
Barbacoa Crispy Tacos                      120.21
Barbacoa Salad Bowl                        106.40
Nantucket Nectar                            98.31
Chicken Salad                               81.09
Chips and Tomatillo-Green Chili Salsa       78.87
Carnitas Crispy Tacos                       77.96
Veggie Soft Tacos                           73.96
Chips and Roasted Chili Corn Salsa          67.85
Izze                                        67.80
Carnitas Salad Bowl                         66.34
Chips and Tomatillo-Red Chili Salsa         59.75
Veggie Salad                                50.94
Burrito                                     44.40
Chips and Roasted Chili-Corn Salsa          43.02
Steak Salad                                 35.66
Bowl                                        29.60
Salad                                       14.80
Crispy Tacos                                14.80
Carnitas Salad                               8.99
Veggie Crispy Tacos                          8.49
Chips and Mild Fresh Tomato Salsa            3.00

In [ ]:
# Chicken Bowl is the most selling and the most expensive product.

In [81]:
'''Task C: Assuming a profit markup of 60% on each product, which product has the highest share in revenue?'''
# IF there is a 60% profit on each product, then there is no need to consider this point.
data.groupby('item_name').agg({'quantity':'sum','item_price':'sum'}).sort_values(by = 'quantity', ascending = False)
# Chicken Bowl has the highest share in revenue.Reason ITs sold the most and has the price item price.

                                       quantity  item_price
item_name
Chicken Bowl                                761     7342.73
Chicken Burrito                             591     5575.82
Chips and Guacamole                         506     2201.04
Steak Burrito                               386     3851.43
Canned Soft Drink                           351      438.75
Chips                                       230      494.34
Steak Bowl                                  221     2260.19
Bottled Water                               211      302.56
Chips and Fresh Tomato Salsa                130      361.36
Canned Soda                                 126      137.34
Chicken Salad Bowl                          123     1228.75
Chicken Soft Tacos                          120     1108.09
Side of Chips                               110      185.90
Veggie Burrito                               97      934.77
Barbacoa Burrito                             91      894.75
Veggie Bowl                                  87      867.99
Carnitas Bowl                                71      736.71
Barbacoa Bowl                                66      672.36
Carnitas Burrito                             60      597.83
Steak Soft Tacos                             56      536.05
6 Pack Soft Drink                            55      356.95
Chips and Tomatillo Red Chili Salsa          50      147.50
Chicken Crispy Tacos                         50      472.13
Chips and Tomatillo Green Chili Salsa        45      132.75
Carnitas Soft Tacos                          40      375.94
Steak Crispy Tacos                           36      357.34
Chips and Tomatillo-Green Chili Salsa        33       78.87
Steak Salad Bowl                             31      343.59
Nantucket Nectar                             29       98.31
Chips and Tomatillo-Red Chili Salsa          25       59.75
Barbacoa Soft Tacos                          25      250.46
Chips and Roasted Chili Corn Salsa           23       67.85
Izze                                         20       67.80
Veggie Salad Bowl                            18      182.50
Chips and Roasted Chili-Corn Salsa           18       43.02
Barbacoa Crispy Tacos                        12      120.21
Barbacoa Salad Bowl                          10      106.40
Chicken Salad                                 9       81.09
Carnitas Crispy Tacos                         8       77.96
Veggie Soft Tacos                             8       73.96
Burrito                                       6       44.40
Veggie Salad                                  6       50.94
Carnitas Salad Bowl                           6       66.34
Bowl                                          4       29.60
Steak Salad                                   4       35.66
Salad                                         2       14.80
Crispy Tacos                                  2       14.80
Chips and Mild Fresh Tomato Salsa             1        3.00
Carnitas Salad                                1        8.99
Veggie Crispy Tacos                           1        8.49

In [107]:
'''Task D: Company is planning is reducing the size of Menu. 
Kindly recommend the menu items to keep and which one to drop. Please explain briefly'''

'Task D: Company is planning is reducing the size of Menu. \nKindly recommend the menu items to keep and which one to drop. Please explain briefly'

In [138]:
product_revenue = data.groupby('item_name').agg({'item_price':'sum'}).sort_values(by =['item_price'],ascending = [False])
total_revenue = data['item_price'].sum()
share=(product_revenue/total_revenue)*100
keep =share[share>= 1]
keep

                                       item_price
item_name
Chicken Bowl                            21.283177
Chicken Burrito                         16.161722
Steak Burrito                           11.163513
Steak Bowl                               6.551245
Chips and Guacamole                      6.379796
Chicken Salad Bowl                       3.561578
Chicken Soft Tacos                       3.211840
Veggie Burrito                           2.709466
Barbacoa Burrito                         2.593466
Veggie Bowl                              2.515901
Carnitas Bowl                            2.135381
Barbacoa Bowl                            1.948861
Carnitas Burrito                         1.732833
Steak Soft Tacos                         1.553761
Chips                                    1.432863
Chicken Crispy Tacos                     1.368486
Canned Soft Drink                        1.271733
Carnitas Soft Tacos                      1.089676
Chips and Fresh Tomato Salsa             1.047415
Steak Crispy Tacos                       1.035763
6 Pack Soft Drink                        1.034633
Steak Salad Bowl                              NaN
Bottled Water                                 NaN
Barbacoa Soft Tacos                           NaN
Side of Chips                                 NaN
Veggie Salad Bowl                             NaN
Chips and Tomatillo Red Chili Salsa           NaN
Canned Soda                                   NaN
Chips and Tomatillo Green Chili Salsa         NaN
Barbacoa Crispy Tacos                         NaN
Barbacoa Salad Bowl                           NaN
Nantucket Nectar                              NaN
Chicken Salad                                 NaN
Chips and Tomatillo-Green Chili Salsa         NaN
Carnitas Crispy Tacos                         NaN
Veggie Soft Tacos                             NaN
Chips and Roasted Chili Corn Salsa            NaN
Izze                                          NaN
Carnitas Salad Bowl                           NaN
Chips and Tomatillo-Red Chili Salsa           NaN
Veggie Salad                                  NaN
Burrito                                       NaN
Chips and Roasted Chili-Corn Salsa            NaN
Steak Salad                                   NaN
Bowl                                          NaN
Salad                                         NaN
Crispy Tacos                                  NaN
Carnitas Salad                                NaN
Veggie Crispy Tacos                           NaN
Chips and Mild Fresh Tomato Salsa             NaN

In [140]:
drop =share[share<1]
drop

                                       item_price
item_name
Chicken Bowl                                  NaN
Chicken Burrito                               NaN
Steak Burrito                                 NaN
Steak Bowl                                    NaN
Chips and Guacamole                           NaN
Chicken Salad Bowl                            NaN
Chicken Soft Tacos                            NaN
Veggie Burrito                                NaN
Barbacoa Burrito                              NaN
Veggie Bowl                                   NaN
Carnitas Bowl                                 NaN
Barbacoa Bowl                                 NaN
Carnitas Burrito                              NaN
Steak Soft Tacos                              NaN
Chips                                         NaN
Chicken Crispy Tacos                          NaN
Canned Soft Drink                             NaN
Carnitas Soft Tacos                           NaN
Chips and Fresh Tomato Salsa                  NaN
Steak Crispy Tacos                            NaN
6 Pack Soft Drink                             NaN
Steak Salad Bowl                         0.995908
Bottled Water                            0.876981
Barbacoa Soft Tacos                      0.725968
Side of Chips                            0.538838
Veggie Salad Bowl                        0.528983
Chips and Tomatillo Red Chili Salsa      0.427534
Canned Soda                              0.398085
Chips and Tomatillo Green Chili Salsa    0.384781
Barbacoa Crispy Tacos                    0.348433
Barbacoa Salad Bowl                      0.308404
Nantucket Nectar                         0.284955
Chicken Salad                            0.235042
Chips and Tomatillo-Green Chili Salsa    0.228608
Carnitas Crispy Tacos                    0.225970
Veggie Soft Tacos                        0.214376
Chips and Roasted Chili Corn Salsa       0.196666
Izze                                     0.196521
Carnitas Salad Bowl                      0.192289
Chips and Tomatillo-Red Chili Salsa      0.173188
Veggie Salad                             0.147651
Burrito                                  0.128695
Chips and Roasted Chili-Corn Salsa       0.124695
Steak Salad                              0.103362
Bowl                                     0.085797
Salad                                    0.042898
Crispy Tacos                             0.042898
Carnitas Salad                           0.026058
Veggie Crispy Tacos                      0.024609
Chips and Mild Fresh Tomato Salsa        0.008696